name: mobile
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bot_toast: ^4.0.4
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  font_awesome_flutter: ^10.5.0
  google_fonts: ^4.0.4
  page_transition: ^2.0.9
  flutter_bloc: ^8.1.3
  lottie: ^2.5.0
  bloc: ^8.1.2
  dio: ^5.3.0
  dart_openai: ^3.0.0
  share_plus: ^7.0.2
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/logo/
    - assets/images/
    - assets/lottie/
